### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by josemarluedke** [neighborly/grpc-auth#2]
The naming of this project can be very confusing with other projects from [grpc-ecosystem/go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware). They have a packages called `grpc_auth` and `validator`. We use the same terms here and they mean different things. 

I propose changing the name of the project to `grpc-authorizer` as well `validator` to `authorizer`.

The function `Validate` in `grpc_auth` should also be renamed to `Authorize`.

**Comment by the-jackalope** [comment]
I agree - a better name would be helpful! Not just confusing, but also precarious when importing/using lots of gRPC middleware in your protos

**Comment by tfeng** [comment]
Any suggestion for a better name?
