### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by josemarluedke** [neighborly/grpc-auth#3]
We should have automated tests to ensure we don't break anything as we continue to develop this further or accept PRs.

- [ ] Create test infrastructure
- [ ] Test the interceptors
- [ ] Add Travis builds

Should we convert the `test` application to be automated tests and create an example application instead?

**Comment by the-jackalope** [comment]
+1 think this would be valuable

**Comment by tfeng** [comment]
Created a test
